CREATE TABLE cms.[_TABLE_TYPE_] (
  id SERIAL, 
  title VARCHAR(256), 
  text TEXT, 
  _user INTEGER NOT NULL, 
  _update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
  _create TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  CONSTRAINT [_TABLE_TYPE_]_pkey PRIMARY KEY(id), 
  CONSTRAINT [_TABLE_TYPE_]_user_fk FOREIGN KEY (_user)
    REFERENCES _user(_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    NOT DEFERRABLE
) WITHOUT OIDS;