CREATE TABLE cms.[_TABLE_] (
  id SERIAL, 
  title VARCHAR(256), 
  text TEXT, 
  source VARCHAR(256), 
  date TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  publish BIT DEFAULT B'0'::bit NOT NULL,
  _user INTEGER NOT NULL, 
  _update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
  _create TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  CONSTRAINT [_TABLE_]_pkey PRIMARY KEY(id), 
  CONSTRAINT [_TABLE_]_user_fk FOREIGN KEY (_user)
    REFERENCES _user(_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    NOT DEFERRABLE
) WITHOUT OIDS;