CREATE TABLE cms.[_TABLE_] (
  id SERIAL, 
  title VARCHAR(256), 
  text TEXT, 
  _user INTEGER NOT NULL, 
  _update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
  _create TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  category INTEGER, 
  url VARCHAR(512), 
  language VARCHAR(128), 
  CONSTRAINT link_pkey PRIMARY KEY(id), 
  CONSTRAINT [_TABLE_TYPE_]_fk FOREIGN KEY (category)
    REFERENCES cms.[_TABLE_TYPE_](id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    NOT DEFERRABLE, 
  CONSTRAINT [_TABLE_]_user_fk FOREIGN KEY (_user)
    REFERENCES _user(_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    NOT DEFERRABLE
) WITHOUT OIDS;